Repository Touchstack/Papertown, pull requests merged in 2024-01, with the labels that each got.

#115 Changes Requested By QA
  src/assets/fonts/Varela-Regular.ttf
  src/index.css
  src/pages/AdminPage/DBRightSection/CMS/CmsPage.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/AddNewPropmt/AddNewPrompt.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/AddNewsItem/AddNewsItem.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/Home/Home.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/Modal/Modal.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/News/News.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/PromptCard/PromptCard.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/WriteNow/WriteNow.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/WritersRoom/WritersRoom.jsx
  tailwind.config.js
Labels: QA in Progress

#114 Problem fixed on the teams page
  src/Component/Modal/JoinUSModal.jsx
  src/pages/AdminPage/DBRightSection/DBRightSection.jsx
  src/pages/AdminPage/DBRightSection/Team/MemberPage.jsx
  src/pages/AdminPage/DBRightSection/Team/Members.jsx
  src/pages/AdminPage/DBRightSection/Team/MembersMain.jsx
  src/pages/AdminPage/DBRightSection/Team/Profile/LoginSessions.jsx
  src/pages/AdminPage/DBRightSection/Team/Profile/MemberProfile.jsx
  src/pages/AdminPage/DBRightSection/Team/Profile/ProfileInfo.jsx
  src/pages/AdminPage/DBRightSection/Team/Roles/Roles.jsx
  src/pages/AdminPage/DBRightSection/Team/Team.jsx
Labels: QA-Stage-1

#113 Five Pop Up Modals [Success & Remove Modals] for Club Profile Page
  src/Component/Modal/Modal.jsx
  src/assets/Images/CoverPhoto.svg
  src/assets/Images/PinkPlus.svg
  src/assets/Images/Rectangle.svg
  src/assets/Images/Tick.svg
  src/assets/Images/UploadIcon.svg
  src/assets/Images/Warning.svg
  src/pages/AdminPage/DBRightSection/Clubs/Clubs.jsx
  src/pages/AdminPage/DBRightSection/Clubs/ManageClub.jsx
  src/pages/AdminPage/DBRightSection/Clubs/NewClub.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/Header.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/ManageClubDetails.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/ManageClubHeader.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/ManageClubSchedule.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/NewClubDetails.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/NewClubHeader.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/NewClubSchedule.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/ProfileHero.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/ProfileMemberList.jsx
  src/pages/AdminPage/DBRightSection/DBRightSection.jsx
Labels: QA-Stage-1

#122 Changes made at QA request
  package-lock.json
  src/assets/Images/edit.png
  src/pages/AdminPage/DBRightSection/Writers/NewWriter.jsx
  src/pages/AdminPage/DBRightSection/Writers/NewWriterForm.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/ProfileBody.jsx
  src/pages/AdminPage/DBRightSection/Writers/WritersBody.jsx
Labels: QA in Progress

#125 Fixed Height issue
  src/Component/SubmitPage/SubmitComponent.jsx
  src/Style/CircleSubmit.css
  src/pages/SubmitPage/SubmitPage.jsx
Labels: QA Approved

#124 Gradient colour on header and Circles
  src/Component/Circle.jsx
  src/Component/Homepage.jsx
  src/Component/RedefiningWriting.jsx
  src/Component/SubmitPage/SubmitBg.jsx
  src/pages/FooterPage/Footer.jsx
  src/pages/Homepage/Homepage.jsx
  src/pages/SubmitPage/SubmitPage.jsx
Labels: QA Approved

#132 Submit page responsiveness and validated form.
  src/Component/SubmitPage/SubmitComponent.jsx
  src/Component/SubmitPage/UploadFile.jsx
  src/assets/Images/submitIdea.png
  src/pages/FooterPage/Footer.jsx
  src/pages/SubmitPage/SubmitPage.jsx
Labels: QA-Stage-1

#133 Implement Logout feature for Paper Town and fixed reversed changes for hero component
  src/Component/RedefiningWriting.jsx
  src/pages/AdminPage/DBRightSection/Clubs/component/ProfileLocation.jsx
  src/pages/ProfilePage/ProfileCardLeft.jsx
Labels: QA-Stage-1

#128 QA changes made
  src/Component/CallToAction/CallToAction.jsx
  src/assets/Images/ChildRightImage.png
  src/pages/AdminPage/DBRightSection/Submissions/Category/NarrativeCards.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/Modal.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/NewSubmissionForm.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/SubmissionsBody.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/SubmissionsCards.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/SubmissionsHeader.jsx
  src/pages/AdminPage/DBRightSection/Writers/NewWriter2.jsx
  src/pages/AdminPage/DBRightSection/Writers/NewWriterForm2.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/Profile.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/ProfileBody.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/ProfileCards.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/ProfileHeader.jsx
  src/pages/AdminPage/DBRightSection/Writers/WriterModal.jsx
  src/pages/AdminPage/DBRightSection/Writers/Writers.jsx
  src/pages/AdminPage/DBRightSection/Writers/WritersBody.jsx
  src/pages/AdminPage/DBRightSection/Writers/WritersSlider.jsx
  src/pages/Homepage/Homepage.jsx
Labels: QA-Stage-2

#141 Writer & Submissions pages adjusted to QA
  package-lock.json
  src/pages/AdminPage/DBRightSection/Submissions/Category/NarrativeCards.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/Modal.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/NewSubmissionForm.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/SubmissionsBody.jsx
  src/pages/AdminPage/DBRightSection/Submissions/Components/SubmissionsCards.jsx
  src/pages/AdminPage/DBRightSection/Submissions/SingleSubmission/SsBody.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/ProfileCards.jsx
  src/pages/AdminPage/DBRightSection/Writers/Profile/ProfileHero.jsx
  src/pages/AdminPage/DBRightSection/Writers/WriterSearchBar.jsx
  src/pages/AdminPage/DBRightSection/Writers/Writers.jsx
  src/pages/AdminPage/DBRightSection/Writers/WritersHeader.jsx
Labels: Needs QA
