Repository Touchstack/Papertown, pull requests merged in 2024-02, with the labels that each got.

#150 Select form input fixed
  src/pages/AdminPage/DBRightSection/Team/MemberForm.jsx
  src/pages/AdminPage/DBRightSection/Team/Profile/ManageBody.jsx
Labels: QA Approved

#149 Sign Up Structure and modals
  package-lock.json
  package.json
  src/Component/RedefiningWriting.jsx
  src/Navbar/GeneralNav.jsx
  src/Navbar/GuardianSignUpForm.jsx/AboutTheChild.jsx
  src/Navbar/GuardianSignUpForm.jsx/AboutYourSelf.jsx
  src/Navbar/GuardianSignUpForm.jsx/GuardianAccountSetUp.jsx
  src/Navbar/SignUpForm/AccountSetupJourney.jsx
  src/Navbar/SignUpForm/GetToKnowYou.jsx
  src/Navbar/SignUpForm/GuardianInformation.jsx
  src/Navbar/SignUpForm/SchoolInformation.jsx
  src/Navbar/SignUpForm/SetUpAccount.jsx
  src/assets/Images/Background.svg
  src/assets/Images/Boy.svg
  src/assets/Images/Circle.svg
  src/assets/Images/Girl.svg
  src/assets/Images/SmallBoy.svg
  src/assets/Images/Smallboy.jpg
  src/assets/Images/arrow-left.svg
  src/main.jsx
Labels: QA-Stage-1

#123 Fixed responsive view for header on HomePage
  src/Component/RedefiningWriting.jsx
  src/pages/Slidershow/OverLay.jsx
Labels: QA Approved

#121 Fixed responsive issue.
  src/pages/AdminPage/DBRightSection/CMS/CmsPage.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/AllPromptCard/AllPromtCard.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/Header/Header.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/Home/Home.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/Modal/Modal.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/NavBar/Navbar.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/NewsAndEvents/NewsAndEvents.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/PromptCard/PromptCard.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/WriteNow/WriteNow.jsx
  src/pages/AdminPage/DBRightSection/CMS/components/WritersRoom/WritersRoom.jsx
  src/pages/AdminPage/DBRightSection/DBRightSection.jsx
Labels: QA Approved

#154 Update to Sign Up Form
  package-lock.json
  package.json
  src/Navbar/GuardianSignUpForm.jsx/GuardianAccountSetUp.jsx
  src/Navbar/SignUpForm/SetUpAccount.jsx
Labels: QA in Progress
